server:
  port: 80
spring:
  http:
    encoding:
      charset: utf-8
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/cloudglasses?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: cloudglasses2018
    password: J7QP6kEGbwY^stD5
    initialSize: 2
    maxActive: 10
    minIdle: 1
    maxWait: 60000
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 30000
    minEvictableIdleTimeMillis: 60000
    validationQuery: SELECT 1
    filters: wall,stat,slf4j,config
    initConnectionSqls: set NAMES utf8mb4;
  jpa:
    open-in-view: true
logging:
  level:
    com.cloudglasses: info
weixin:
  appid: wx8587fd25a63e8242
  secret: 6e7581bfbee2ff3807158c1b49f49a5e
  token: cloudglasses2018
  aesKey: 9MidPZtZnlBXYOZMPdBcpAZP9mIEpsHESx5yqjpGIjR